#==============================数据库相关配置========================================
#数据库配置

spring:
  cache:
    type: redis
    redis:
      cache-null-values: true

  redis:
    host: 47.98.122.108
    port: 6379
    password: stone123456

#配置数据源
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://rm-bp1000emxfsi8snprao.mysql.rds.aliyuncs.com:3306/stone?serverTimezone=GMT%2B8
      username: njuptwly
      password: Wly771013!

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  mvc:
    static-path-pattern: /media/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${media.dir}

#    #指定redis底层客户端实现
#    client-type: lettuce
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#
#        # 连接池中的最大空闲连接
#        max-idle: 10
#
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.stone.demo.model
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: enabled
      logic-delete-value: 0
      logic-not-delete-value: 1

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: Zmpqc2Q9ODcyZHNkZjIzM2OkNFJFUkZhMzIzMjQzMlJkaWHzMnIyMzk4dTMyamZra3NXMjMxM1QyMzMmKiZqZUxKRiZeKjFHTExQO0RKODk4NDNqcmUoKGlvZXdqZktKRE8zMnhjY08yS0ZLTlNmZ2hqb3AtPTFSV0VIUkVXRVc=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
uploadFile:
  path: \Desktop\file\
#  path: /home/opensource_startup/file/
  # 文件大小 /M
  maxSize: 5

# 微信小程序配置
wxMini:
  appId: wx46394ebb0d814a8e
  secret: 8207dc606e9ae70ac5ef8696100dd393




