#==============================数据库相关配置========================================
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1000emxfsi8snprao.mysql.rds.aliyuncs.com:3306/www?serverTimezone=GMT%2B8
    username: njuptwly
    password: Wly771013!
  redis:
    host: 47.98.122.108
    port: 6379
    password: stone123456
    #指定redis底层客户端实现
    client-type: lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10

        # 连接池中的最大空闲连接
        max-idle: 10

        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl